{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-14 00:21:33.911363", "error": "redis.exceptions.ConnectionError", "errormsg": "Error 10061 connecting to 127.0.0.1:6379. 由于目标计算机积极拒绝，无法连接。.", "errorpath": ["File \"D:\\Projects\\ztx\\server\\rbac\\views.py\", line 80, in post", "File \"D:\\Projects\\ztx\\server\\libs\\authtication.py\", line 43, in create_token"], "method": "POST", "url": "/rbac/login", "user": null, "params": {}, "data": {"username": "admin", "password": "admin"}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-14 09:14:07.753531", "error": "django.db.utils.OperationalError", "errormsg": "table ztx_trade has no column named price", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 209, in post"], "method": "POST", "url": "/ztx/consume", "user": null, "params": {}, "data": {"id": 2, "name": "矿泉水", "product_id": 1, "price": 11}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-14 09:14:22.958030", "error": "django.db.utils.OperationalError", "errormsg": "table ztx_trade has no column named price", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 209, in post"], "method": "POST", "url": "/ztx/consume", "user": null, "params": {}, "data": {"id": 2, "name": "矿泉水", "product_id": 2, "price": 1}}
